name: projeto_it
version: "1.0.0"
config-version: 2

profile: projeto_it

model-paths: ["dbt/models"]
test-paths: ["dbt/tests"]
macro-paths: ["dbt/macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  projeto_it:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: marts
      +materialized: table